export * from "./chatGateway";
export * from "./chatGateway.types";
export { decodeAudioBase64, AudioBase64DecodeError } from "./audioFromBase64";
export {
  chatResponseCache,
  buildRequestKey,
  parseCacheControlMaxAgeMs,
  type CachedReplyEntry,
} from "./chatResponseCache";

// Python Backend — Agendamento IA
export {
  getPythonBackendConfig,
  initializeChatSession,
  sendChatMessage,
  createWhatsAppInstance,
  getWhatsAppQrCode,
  createTenant,
  getTenantById,
  updateTenant,
  deleteTenant,
  searchTenants,
  getKnowledgeBase,
  saveKnowledgeBase,
  deleteKnowledgeBase,
  getTenantUsage,
  getMessageLimitConfig,
  listGlobalRecipients,
  createGlobalRecipient,
  updateGlobalRecipient,
  deleteGlobalRecipient,
} from "./pythonBackend";
export type {
  PythonBackendConfig,
  PythonChatRequest,
  PythonChatSuccessResponse,
  PythonChatErrorResponse,
  PythonChatSuccess,
  PythonChatFailure,
  PythonChatResult,
  PythonChatInitSuccessResponse,
  PythonChatInitErrorResponse,
  PythonChatInitSuccess,
  PythonChatInitFailure,
  PythonChatInitResult,
  CreateWhatsAppInstanceRequest,
  CreateWhatsAppInstanceResponse,
  CreateWhatsAppInstanceResult,
  WhatsAppQrCodeResponse,
  WhatsAppQrCodeResult,
  WhatsAppOperationFailure,
  Tenant,
  TenantCreateInput,
  TenantWriteInput,
  TenantFieldErrors,
  TenantOperationFailure,
  TenantOperationResult,
  TenantDeleteResult,
  TenantSearchItem,
  TenantSearchSuccess,
  TenantSearchFailure,
  TenantSearchResult,
  KnowledgeBase,
  KnowledgeBaseReadSuccess,
  KnowledgeBaseWriteSuccess,
  KnowledgeBaseDeleteSuccess,
  KnowledgeBaseFailure,
  KnowledgeBaseReadResult,
  KnowledgeBaseWriteResult,
  KnowledgeBaseDeleteResult,
  TenantUsage,
  TenantUsageResult,
  TenantMessageLimitConfig,
  TenantMessageLimitConfigResult,
  GlobalRecipient,
  GlobalRecipientListResult,
  GlobalRecipientOperationResult,
  GlobalRecipientDeleteResult,
  GlobalRecipientFailure,
} from "./pythonBackend.types";

// Prompt Manager — Prompts & Guardrails
export {
  fetchGuardrails,
  createGuardrail,
  updateGuardrail,
  deleteGuardrail,
  fetchPrompts,
  createPrompt,
  updatePrompt,
  deletePrompt,
  linkTenantToPrompt,
  fetchTenantPromptDetail,
} from "./promptManager";
export type {
  Guardrail,
  Prompt,
  GuardrailCreateInput,
  GuardrailUpdateInput,
  PromptCreateInput,
  PromptUpdateInput,
  TenantLinkInput,
  TenantPromptDetail,
  PromptManagerResult,
  GuardrailListResult,
  GuardrailSingleResult,
  PromptListResult,
  PromptSingleResult,
  TenantLinkResult,
  TenantPromptDetailResult,
  DeleteResult,
} from "./promptManager.types";

// Session Manager — Thread ID
export { getThreadId, resetThreadId } from "./sessionManager";
